// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/biodebox/go-coge-sql/pkg/models"

// Configurator is an autogenerated mock type for the Configurator type
type Configurator struct {
	mock.Mock
}

// GetHydrator provides a mock function with given fields:
func (_m *Configurator) GetHydrator() models.Hydrator {
	ret := _m.Called()

	var r0 models.Hydrator
	if rf, ok := ret.Get(0).(func() models.Hydrator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Hydrator)
		}
	}

	return r0
}

// GetTransformer provides a mock function with given fields:
func (_m *Configurator) GetTransformer() models.Transformer {
	ret := _m.Called()

	var r0 models.Transformer
	if rf, ok := ret.Get(0).(func() models.Transformer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Transformer)
		}
	}

	return r0
}
