// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/biodebox/go-coge-sql/pkg/models"

// Transformer is an autogenerated mock type for the Transformer type
type Transformer struct {
	mock.Mock
}

// Transform provides a mock function with given fields:
func (_m *Transformer) Transform() ([]*models.Table, error) {
	ret := _m.Called()

	var r0 []*models.Table
	if rf, ok := ret.Get(0).(func() []*models.Table); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Table)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
